import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jinpu Li</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello<a>!</a>
        </h1>
        <p className={styles.description}>
          Welcome to Jinpu Li&apos;s homepage.
        </p>
      </main>

      <footer className={styles.footer}>
        
          Copyright © Jinpu Li 2022. All Rights Reserved.
        
      </footer>
    </div>
  )
}
